/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistsRouteImport } from './routes/wishlists'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConciergeRouteImport } from './routes/concierge'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as InboxIndexRouteImport } from './routes/inbox.index'
import { Route as TripsTripIdRouteImport } from './routes/trips.$tripId'
import { Route as StaysStayIdRouteImport } from './routes/stays.$stayId'
import { Route as InboxChatIdRouteImport } from './routes/inbox.$chatId'
import { Route as CheckoutStayIdRouteImport } from './routes/checkout.$stayId'

const WishlistsRoute = WishlistsRouteImport.update({
  id: '/wishlists',
  path: '/wishlists',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeRoute = ConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysStayIdRoute = StaysStayIdRouteImport.update({
  id: '/stays/$stayId',
  path: '/stays/$stayId',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxChatIdRoute = InboxChatIdRouteImport.update({
  id: '/inbox/$chatId',
  path: '/inbox/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutStayIdRoute = CheckoutStayIdRouteImport.update({
  id: '/checkout/$stayId',
  path: '/checkout/$stayId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/concierge': typeof ConciergeRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/wishlists': typeof WishlistsRoute
  '/checkout/$stayId': typeof CheckoutStayIdRoute
  '/inbox/$chatId': typeof InboxChatIdRoute
  '/stays/$stayId': typeof StaysStayIdRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/inbox/': typeof InboxIndexRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/concierge': typeof ConciergeRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/wishlists': typeof WishlistsRoute
  '/checkout/$stayId': typeof CheckoutStayIdRoute
  '/inbox/$chatId': typeof InboxChatIdRoute
  '/stays/$stayId': typeof StaysStayIdRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/inbox': typeof InboxIndexRoute
  '/trips': typeof TripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/concierge': typeof ConciergeRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/wishlists': typeof WishlistsRoute
  '/checkout/$stayId': typeof CheckoutStayIdRoute
  '/inbox/$chatId': typeof InboxChatIdRoute
  '/stays/$stayId': typeof StaysStayIdRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/inbox/': typeof InboxIndexRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget'
    | '/concierge'
    | '/login'
    | '/map'
    | '/onboarding'
    | '/profile'
    | '/recommendations'
    | '/settings'
    | '/wishlists'
    | '/checkout/$stayId'
    | '/inbox/$chatId'
    | '/stays/$stayId'
    | '/trips/$tripId'
    | '/inbox/'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budget'
    | '/concierge'
    | '/login'
    | '/map'
    | '/onboarding'
    | '/profile'
    | '/recommendations'
    | '/settings'
    | '/wishlists'
    | '/checkout/$stayId'
    | '/inbox/$chatId'
    | '/stays/$stayId'
    | '/trips/$tripId'
    | '/inbox'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/budget'
    | '/concierge'
    | '/login'
    | '/map'
    | '/onboarding'
    | '/profile'
    | '/recommendations'
    | '/settings'
    | '/wishlists'
    | '/checkout/$stayId'
    | '/inbox/$chatId'
    | '/stays/$stayId'
    | '/trips/$tripId'
    | '/inbox/'
    | '/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetRoute: typeof BudgetRoute
  ConciergeRoute: typeof ConciergeRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SettingsRoute: typeof SettingsRoute
  WishlistsRoute: typeof WishlistsRoute
  CheckoutStayIdRoute: typeof CheckoutStayIdRoute
  InboxChatIdRoute: typeof InboxChatIdRoute
  StaysStayIdRoute: typeof StaysStayIdRoute
  TripsTripIdRoute: typeof TripsTripIdRoute
  InboxIndexRoute: typeof InboxIndexRoute
  TripsIndexRoute: typeof TripsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlists': {
      id: '/wishlists'
      path: '/wishlists'
      fullPath: '/wishlists'
      preLoaderRoute: typeof WishlistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge': {
      id: '/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof ConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays/$stayId': {
      id: '/stays/$stayId'
      path: '/stays/$stayId'
      fullPath: '/stays/$stayId'
      preLoaderRoute: typeof StaysStayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$chatId': {
      id: '/inbox/$chatId'
      path: '/inbox/$chatId'
      fullPath: '/inbox/$chatId'
      preLoaderRoute: typeof InboxChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$stayId': {
      id: '/checkout/$stayId'
      path: '/checkout/$stayId'
      fullPath: '/checkout/$stayId'
      preLoaderRoute: typeof CheckoutStayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetRoute: BudgetRoute,
  ConciergeRoute: ConciergeRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RecommendationsRoute: RecommendationsRoute,
  SettingsRoute: SettingsRoute,
  WishlistsRoute: WishlistsRoute,
  CheckoutStayIdRoute: CheckoutStayIdRoute,
  InboxChatIdRoute: InboxChatIdRoute,
  StaysStayIdRoute: StaysStayIdRoute,
  TripsTripIdRoute: TripsTripIdRoute,
  InboxIndexRoute: InboxIndexRoute,
  TripsIndexRoute: TripsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
